definitions:
  internal.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  internal.Task:
    properties:
      completed:
        description: Completed if it's complete or not
        type: boolean
      id:
        description: Id uniqe for each task
        type: integer
      title:
        description: Title descripe each task
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks:
    get:
      description: Get a list of all tasks
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            items:
              $ref: '#/definitions/internal.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
      summary: Get all tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Add a new task to the list
      parameters:
      - description: New task object
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/internal.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
      summary: Add a new task
      tags:
      - tasks
    put:
      description: Update a task with new information
      parameters:
      - description: Task object that needs to be updated
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/internal.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully updated
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
      summary: Update a task
  /tasks/{id}:
    delete:
      description: Delete a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.ErrorResponse'
      summary: Delete a task by ID
swagger: "2.0"
