name: Full Stack

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: Install dependencies
        run: cd ./backend && go get -d ./...

      - name: Run Tests
        run: cd ./backend && go test -v ./...

      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: 2022.1.3
          working-directory: ./backend/

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          working-directory: ./backend/

      - name: Run gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: ./
          gofmt-flags: -l -d
          working-directory: ./backend/

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend
